FROM balenalib/%%BALENA_MACHINE_NAME%%-debian
WORKDIR /app
ADD . /app/
RUN install_packages apt-transport-https libcap2-bin jq && \
    echo "deb https://packages.grafana.com/oss/deb stable main" > /etc/apt/sources.list.d/grafana.list && \
    curl https://packages.grafana.com/gpg.key | apt-key add - && \
    apt-get update && \
    install_packages wget adduser libfontconfig grafana && \
    chown -R root:grafana /app/provisioning
CMD [ "/app/entry.sh" ]
