FROM balenalib/%%BALENA_MACHINE_NAME%%-debian
WORKDIR /app
ADD . /app/
RUN install_packages wget adduser libfontconfig && \
wget -q https://dl.grafana.com/oss/release/grafana_5.4.2_amd64.deb && \
dpkg -i grafana_5.4.2_amd64.deb && \
chown -R root:grafana /app/provisioning
CMD [ "/app/entry.sh" ]
